[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies.sea-orm]
version = "0.10.6"

[dependencies]
chrono = "0.4.23"
serde = { version = "1.0.152", features = ["derive"] }
